### ISSUE TITLE
post error in readRDS readitem

### ISSUE THREAD

**Issue by roelhogervorst** [RMHogervorst/rwethereyet#6]
I had a problem with bigrquery

- my laptop crashed (happens sometimes)
- this corrupted (I think) the .httr-oauth file in my folder
- the error is extremely not helpful:

```
Error in readRDS(cache_path) : 
  ReadItem: unknown type 97, perhaps written by later version of R
```

Solution: delete the .httr-oath token

What I did:
remove the rstudio files

check if there were similar issues with bigrquery (nope)
find if there was a ~/.Rdata file (There wasn't)
remove hidden rstudio project files
remove .RProject file

slightly helpful: create a new project, and run the query there: no problems but reauth.

**Comment by RMHogervorst** [comment]
fixed

**Comment by roelhogervorst** [comment]
https://notes.rmhogervorst.nl/post/2017/11/17/issue-error-in-readrds-bigquery/

**Comment by roelhogervorst** [comment]
now with gargle things are quite a bit easier. delete the token, 
run again. If you are on a vm, use oob (out of bound ) authentification.
https://bigrquery.r-dbi.org/#important-details
https://gargle.r-lib.org/articles/how-gargle-gets-tokens.html
